---
title: "Mapa de infraestructura verde del Corredor Biológico Interurbano María Aguilar"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leaflet.opacity)
library(leafem)
library(esri2sf)
library(raster)

#--------- URL de geoservicios y datos ------------

url_agfs_limite_cbima <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_cbi_maria_aguilar/FeatureServer/0"

url_raster_infraestructura_verde <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/infraestructura-verde/cbima/IV_CBI_RIO_MARIA_AGUILAR_WEB.TIF"

#--------------- Objetos sf y raster --------------

# Límite del CBIMA
sf_limite_cbima <- 
  esri2sf(url_agfs_limite_cbima)

# Límite del CBIMA (reproyectado a Web Mercator)
sf_limite_cbima_web <- 
  sf_limite_cbima %>%
  st_transform(3857)

# Capa raster de infraestructura verde (en Web Mercator)
raster_infraestructura_verde <-
  raster(url_raster_infraestructura_verde) %>%
  aggregate(fact=c(2), fun=modal) %>% # ¡¡HAY QUE TRATAR DE ELIMINAR ESTA AGRUPACIÓN. PODRÍA FUNCIONAR AL USAR MÁS MEMORIA LINUX!!
  crop(sf_limite_cbima_web) %>%
  mask(sf_limite_cbima_web)

#---------------- Paletas de colores ---------------

colores_infraestructura_verde <- 
  c(rgb(43,99,89,   maxColorValue=255), rgb(110,186,148,maxColorValue=255), 
    rgb(255,102,102,maxColorValue=255), rgb(111,216,208,maxColorValue=255),
    rgb(178,209,225,maxColorValue=255), rgb(177,207,117,maxColorValue=255),
    rgb(210,172,226,maxColorValue=255), rgb(236,243,228,maxColorValue=255), 
    rgb(204,204,204,maxColorValue=255), rgb(168,97,186, maxColorValue=255),
    rgb(95,68,170,  maxColorValue=255), rgb(105,114,84, maxColorValue=255), 
    rgb(239,147,111,maxColorValue=255), rgb(153,96,83,  maxColorValue=255), 
    rgb(170,164,109,maxColorValue=255))

etiquetas_infraestructura_verde <- 
  c("Bosques y arbolados periurbanos", "Bosques y arbolados en riberas de ríos", 
    "Parques y jardines pequeños", "Campos deportivos y recreativos", 
    "Lagunas estacionales de agua dulce", "Arbolados dispersos", 
    "Terrenos baldíos (matorrales)", "Superficie no pavimentada", 
    "Superficie pavimentada", "Arbolados a lo largo de vías férreas", 
    "Arbolados a lo largo de autopistas", "Pastos cultivados", 
    "Cultivos perennes", "Cafetales arbolados",
    "Terrenos baldíos (pastos)")

values_infraestructura_verde <- 
  c(1, 3, 
    4, 7, 
    8, 9, 
    10, 11, 
    12, 14, 
    15, 19, 
    20, 21, 
    22)

pal <- colorFactor(
  palette = colores_infraestructura_verde, 
  domain = values_infraestructura_verde,
  na.color = "transparent"
)

```

Row
-----------------------------------------------------------------------

###
```{r}

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_cbima,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite del CBIMA"
  ) %>%
  addRasterImage(
    raster_infraestructura_verde, 
    layerId = "raster",
    colors = pal, 
    opacity = 1,
    group = "Infraestructura verde"
  ) %>%
  addLegend(
    title = "Infraestructura verde", 
    position = "bottomright",
    colors = colores_infraestructura_verde, 
    opacity = 1,
    labels = etiquetas_infraestructura_verde,
    group = "Infraestructura verde"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite del CBIMA", "Infraestructura verde"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates() %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addOpacitySlider(layerId = "raster")

```